language: node_js
dist: trusty
node_js:
- '6.10'
addons:
  chrome: stable
cache:
  directories:
  - node_modules
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sleep 3
- google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost
  &
before_deploy:
- npm run buildProd
- cp src/404.html dist/
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: dist
  on:
    branch: pages
  github_token:
    secure: jabBFVhFbKMFkmb0odbvd/PxmJmskLhNPsaIJkSDsQXg9yZtHu4H7CDYhijo+H3QLsjIl1WoA1Iz2mtgvOO8vtdaEAwHipJnE8aTzV1hKOiSc4QKahJCnTykJS/G5uoGIhokdt/xYkASCyZP6tCm/Syl6aD/paOx7fUpy6j+Iks8FMbBZH+Cdq8vp9jyMyMX/8tqbMKDy7Yi+M2FiAy49Du/U4GXvEwtwFRiRoXRjKyW07oQWIRLsU003PvAOKYuIAuWzxurmTogL7Tog6cNDhyreYaJ8y3MxlTs/R2H6zpPPiB8p0Dl6gbkJNCClgMNTyqybbS0MAhcEfddH1hTNxrHEw9L+jx7x+I5MrtaOw/9YVAebfu2jsw1lZJgJtgkfmmoNDtonrYqe+RZMdoefZ+efutGM7P3UOgU9TUPA99gOh+elJmmADl2JhncsMouxjVEVRi+lIUWragh48DJ+gd2FOV+4dvcXs45wwVQRgdo9nNXhghx6fYTg8CA3JTUUKssMhDFJm+KUEZmF0sX93SQznMGzVNHkvXZjr+QcsdHZ8HKeOVDb0xOA4dlifFpPEczwyE/xRV1f26WDzrbKebijpS/LOTH5fu0TdFMkxuwa0DCP7RONRau8vwonFgrV106LuE+eq7LN8rv4BpTiv7rJlhs9jRX8IDDdS/Uu4Q=
notifications:
  slack:
    secure: jfWLbuzJb8jcm5J7e8AUSWhTB+idbtaMpxea8v4rwstytX1BvbWmzhiUu7qJ0elYNFrNV681HlRehwKmsa5QinDRWlcNorRy7bKANEDG5Gr/VrGlTfYFslqEp9kGAyKWE5aR5rndCvEYTX3LVJQkNrQ4C/t/GoVqwiis5550nDW5vIIWrMzRrYBVDtEoRMCwUaYgaOSQoDFHUp5l1WdpikGDZ6s2m/WWzJDf5gc9Lx5o5nyy12P4Kx6XUrZ+6nQuCfaQkIUGDBME/k+So3r1lE/EV9Vf5olyez2Sf4EnntNPtc0uGrRju6Cnwff/lHM7HXMUreFEiUyAlEpSyV/khrY6Su+1gFq1lOVJStGlmFve59H6j4HzdGbhh7wXgEkF49zfW1GSayo//5/baXht63PIpUinZVk2PUW3WlbsO7b1zcMORRk3TGCg9G/y4XfGNupreP5n7/NOs3otvcQPH4GdXxd0SwId+bgLHnsJNdYG+K9yyawctf6yTAFJkQR5ydgsG0UBBGoALkz4EMu8ruuizqo7la6+9uzbGua9iaITvYBBuZyEPgJliIFgWoS6wf9tZOap6s/vBTaX6cfJxM1XDdDib+j53Mr6nCPKMb0yya1nYu4/B1wDywZKdUXDeOAkHgdnakoEzFw/ACgqgpdSlb2h9ICJwSNvaVmn2Mc=
