service: gym-legacy
custom:
  auth0: ${file(.auth0.yml)}
provider:
  name: aws
  runtime: nodejs6.10
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:PutItem
      Resource:
        Fn::Join:
        - ':'
        - - arn
          - aws
          - dynamodb
          - Ref: 'AWS::Region'
          - Ref: 'AWS::AccountId'
          - 'table/active_programs'
  environment:
    AUTH0_DOMAIN: ${self:custom.auth0.AUTH0_DOMAIN}
    AUTH0_BACKEND_CLIENT_ID: ${self:custom.auth0.AUTH0_BACKEND_CLIENT_ID}
    AUTH0_BACKEND_CLIENT_SECRET: ${self:custom.auth0.AUTH0_BACKEND_CLIENT_SECRET}
functions:
  userinfo:
    handler: userinfo.get
    events:
      - http:
          path: user/info
          method: get
          authorizer: auth
          cors: true
  activateWorkout:
    handler: userinfo.post
    events:
      - http:
          path: user/activateWorkout
          method: post
          authorizer: auth
          cors: true
          request:
            parameters:
              querystrings:
                url: true
  deactivateWorkout:
    handler: userinfo.delete
    events:
      - http:
          path: user/deactivateWorkout
          method: DELETE
          authorizer: auth
          cors: true
          request:
            parameters:
              querystrings:
                url: true
  createActiveProgram:
    handler: activeProgram.create
    events:
      - http:
          path: user/program
          method: POST
          authorizer: auth
          cors: true
  auth:
    handler: auth.authenticate
resources:
  Resources:
    usersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: active_programs
        AttributeDefinitions:
          - AttributeName: user_id
            AttributeType: S
          - AttributeName: start_date
            AttributeType: S
        KeySchema:
          - AttributeName: user_id
            KeyType: HASH
          - AttributeName: start_date
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
