service: gym-legacy
custom:
  auth0: ${file(.auth0.yml)}
provider:
  name: aws
  runtime: nodejs6.10
  environment:
    AUTH0_DOMAIN: ${self:custom.auth0.AUTH0_DOMAIN}
    AUTH0_BACKEND_CLIENT_ID: ${self:custom.auth0.AUTH0_BACKEND_CLIENT_ID}
    AUTH0_BACKEND_CLIENT_SECRET: ${self:custom.auth0.AUTH0_BACKEND_CLIENT_SECRET}
functions:
  userinfo:
    handler: userinfo.get
    events:
      - http:
          path: user/info
          method: get
          authorizer: auth
  auth:
    handler: auth.authenticate
